//html regarding the manager section. if no manager, return an empty string
const createManager = manager => {
    if (!manager) {
      return '';
    }
    const { managerName, managerId, managerEmail, managerRole, managerOffice } = {...manager};
      return `
        <section class="my-3 d-flex" id="manager">
            <h1 class="text-dark bg-info display-inline-block">name: ${managerName}</h1>
            <h2 class="text-dark bg-info display-inline-block">role: ${managerRole}</h2>
            <h3 class="text-dark bg-info display-inline-block">employee id: ${managerId}</h3>
            <h3 class="text-dark bg-info display-inline-block">
                <a href="mailto:${managerEmail}">${managerEmail}</a></h3>
            <h3 class="text-dark bg-info display-inline-block">office: ${managerOffice}</h3>
        </section>
       `
};

//html regarding the engineer section. if no engineer, return an empty string
const createEngineer = engineer => {
  if (!engineer) {
    return '';
  }
    const { engineerName, engineerId, engineerEmail, engineerRole, engineerGithub } = {...engineer};
      return `
        <section class="my-3 d-flex" id="engineer">
            <h1 class="text-dark bg-info display-inline-block">name: ${engineerName}</h1>
            <h2 class="text-dark bg-info display-inline-block">role: ${engineerRole}</h2>
            <h3 class="text-dark bg-info display-inline-block">employee id: ${engineerId}</h3>
            <h3 class="text-dark bg-info display-inline-block">
                <a href="mailto:${engineerEmail}">${engineerEmail}</a></h3>
            <h3 class="text-dark bg-info display-inline-block">office: ${engineerGithub}</h3>
                <a href="${engineerGithub}">${engineerGithub}</a></h3>
        </section>
      `
  };

//html regarding the intern section. if no intern, return an empty string
const createIntern = intern => {
    if (!intern) {
      return '';
    }
    const { internName, internId, internEmail, internRole, internSchool } = {...intern};
      return `
        <section class="my-3 d-flex" id="intern">
            <h1 class="text-dark bg-primary display-inline-block">name: ${internName}</h1>
            <h2 class="text-dark bg-primary display-inline-block">role: ${internRole}</h2>
            <h3 class="text-dark bg-primary display-inline-block">employee id: ${internId}</h3>
            <h3 class="text-dark bg-primary display-inline-block">
                <a href="mailto:${internEmail}">${internEmail}</a></h3>
            <h3 class="text-dark bg-primary display-inline-block">college or university: ${internSchool}</h3>
        </section>
      `
  };

  const renderHTML = (team) => {
    let htmlFile = `
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>employee generator!</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@200&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="style.css">
    </head>
      <body>
        <header>
          <div class="container flex-flow justify-space-between align-center py-3">
            <h1 class="page-title text-secondary bg-dark py-2 px-3">employee generator</h1>
            <h2 class="page-title text-secondary">use the cli to generate a full list of your employees.</h2>
          </div>
        </header>
        <main>`;

        for (manager of team) {
          htmlFile += createManager(manager);
        }
        for (engineer of team) {
          htmlFile += createEngineer(engineer);
          }
        for (intern of team) {
          htmlFile += createIntern(intern);
        }


        // if (manager) {
        //   console.log(managerRole);
        //   //htmlFile += createManager();
        // }
        // if (engineerRole) {
        //   console.log(engineerRole);
        //   //htmlFile += createEngineer();
        // }
        // if (internRole) {
        //   console.log(internRole);
        //   //htmlFile += createIntern();
        // }

      htmlFile += `</main>
      <footer>generated by node.js</footer>`
      return htmlFile;
    
  }

module.exports = { renderHTML }